site_name: مستندات ERP تابان
site_description: توضیحات پروژه شما اینجا قرار می‌گیرد.
site_author: تابان‌سافت
site_url: https://docs.tabansoft.ir
repo_url: https://github.com/tabansoft/taban-erp-docs/

theme:
  name: material
  language: fa
  direction: rtl
  font:
    text: Vazirmatn
    code: Fira Code

nav:
  - "معرفی": index.md
  - "ساختار سازمان":
      - "ساختار مالی":
          - "بنگاه‌های اقتصادی": enterprise-structure/financial/legal-entity.md
      - "ساختار عملیاتی":
          - "مکان‌های عملیاتی": enterprise-structure/operational/operating-unit.md
  - "مالی":
      - "خزانه‌داری":
          - "معرفی ماژول خزانه‌داری": "financial/treasury/overview.md"
          - "تعاریف پایه":
              - "صندوق‌های نقدی": financial/treasury/master-data/cash-box.md
              - "صندوق‌های اسناد": financial/treasury/master-data/document-box.md
              - "بانک‌ها": financial/treasury/master-data/bank.md
              - "‌شعب بانک‌ها": financial/treasury/master-data/bank-branch.md
              - "حساب‌های بانکی": financial/treasury/master-data/bank-account.md
              - "دسته‌چک‌ها": financial/treasury/master-data/checkbook.md
              - "روش‌های پرداخت": financial/treasury/master-data/payment-method.md
          - "عملیات":
              - "ثبت دریافت/پرداخت": financial/treasury/transactions/payment-receipt-document.md
              - "تسویه حساب": financial/treasury/transactions/settlement.md
          - "مدیریت چک‌های دریافتی":
              - "مقدمه": financial/treasury/received-check-management/overview.md
              - "دریافت چک جدید": financial/treasury/received-check-management/receipt-check.md
              - "واگذاری چک به بانک": financial/treasury/received-check-management/deposite-check.md
              - "اعلام وصول/برگشت چک": financial/treasury/received-check-management/clearance-check.md
              - "خرج کردن چک": financial/treasury/received-check-management/endorsement-check.md
              - "استرداد چک": financial/treasury/received-check-management/return-check.md
          - "عملیات دوره‌ای":
              - "مغایرت بانکی": financial/treasury/periodic-operations/bank-reconciliation.md
      - "حسابداری":
          - "معرفی ماژول حسابداری": "financial/accounting/overview.md"
  # - 'فروش':
  #   - 'اطلاعات پایه':
  #     - 'واحد فروش': sales/operational/operating-unit.md
  #     - 'کانال توزیع': sales/operational/operating-unit.md
  #     - 'مشتری': sales/operational/operating-unit.md
  #   - 'سفارش فروش': sales/operational/operating-unit.md
  # - 'قیمت‌گذاری':
  #   - 'لیست قیمت': sales/operational/operating-unit.md
  #   - 'تعدیلات قیمت': sales/operational/operating-unit.md
  #   - 'قوانین تعدیلات قیمت': sales/operational/operating-unit.md

  - "مدیریت موجودی":
      - "تعاریف پایه":
          - "انواع بسته‌بندی کالا": inventory-management/master-data/package-type.md

  - "مدیریت انبار":
      - "تعاریف پایه":
          - "انواع بسته‌بندی کالا": inventory-management/master-data/package-type.md

  - "برنامه‌ریزی و کنترل تولید":
      - "تعاریف پایه":
          - "قابلیت‌ها": manufacturing/master-data/capability.md
          - "انواع منبع": manufacturing/master-data/resource-type.md
          - "منابع": manufacturing/master-data/resource.md
          - "مراکز کار": manufacturing/master-data/work-center.md
          - "قواعد تخصیص": manufacturing/master-data/dispatching-rule.md
          - "موتور زمان‌بندی": manufacturing/master-data/sheduler.md
      - "مهندسی تولید":
          - "فرمول‌های تولید": manufacturing/production-engineering/bom.md
          - "فرآیند‌های تولید": manufacturing/production-engineering/routing.md
      - "برنامه‌ریزی":
          - "برنامه‌های تولید اصلی": manufacturing/planning/master-production-schedules.md
      - "اجرای تولید":
          - "دستور‌های تولید": manufacturing/planning/resources.md

  - "مدیریت حمل‌ونقل":
      - "تعاریف پایه":
          - "انواع وسیله نقلیه": transportation-management/master-data/vehicle-type.md
