site_name: مستندات ERP تابان
site_description: توضیحات پروژه شما اینجا قرار می‌گیرد.
site_author: تابان‌سافت
site_url: https://docs.tabansoft.ir
repo_url: https://github.com/tabansoft/taban-erp-docs/

theme:
  name: material
  language: fa
  direction: rtl
  font:
    text: Vazirmatn
    code: Fira Code

nav:
  - 'معرفی': index.md
  - 'ساختار سازمان':
    - 'ساختار مالی':
      - 'بنگاه اقتصادی': enterprise-structure/financial/legal-entity.md
    - 'ساختار عملیاتی':
      - 'مکان عملیاتی': enterprise-structure/operational/operating-unit.md
  # - 'فروش':
  #   - 'اطلاعات پایه':
  #     - 'واحد فروش': sales/operational/operating-unit.md
  #     - 'کانال توزیع': sales/operational/operating-unit.md
  #     - 'مشتری': sales/operational/operating-unit.md
  #   - 'سفارش فروش': sales/operational/operating-unit.md
    # - 'قیمت‌گذاری':
    #   - 'لیست قیمت': sales/operational/operating-unit.md
    #   - 'تعدیلات قیمت': sales/operational/operating-unit.md
    #   - 'قوانین تعدیلات قیمت': sales/operational/operating-unit.md
  
  - 'مدیریت موجودی':
    - 'تعاریف پایه':
      - 'انواع بسته‌بندی کالا': inventory-management/master-data/package-type.md

  - 'مدیریت انبار':
    - 'تعاریف پایه':
      - 'انواع بسته‌بندی کالا': inventory-management/master-data/package-type.md

  - 'برنامه‌ریزی و کنترل تولید':
    - 'تعاریف پایه':
      - 'قابلیت‌ها': manufacturing/master-data/capability.md
      - 'انواع منبع': manufacturing/master-data/resource-type.md
      - 'منابع': manufacturing/master-data/resource.md
      - 'مراکز کاری': manufacturing/master-data/work-center.md
      - 'فرمول‌های تولید': manufacturing/master-data/bom.md
      - 'فرآیند‌های تولید': manufacturing/master-data/routing.md
      - 'قواعد تخصیص': manufacturing/master-data/dispatching-rules.md
      - 'موتور زمان‌بندی': manufacturing/master-data/sheduler.md
    - 'برنامه‌ریزی':
      - 'برنامه‌های تولید اصلی': manufacturing/planning/master-production-schedules.md
    - 'اجرای تولید':
      - 'دستور‌های تولید': manufacturing/planning/resources.md
      
    

  - 'مدیریت حمل‌ونقل':
    - 'تعاریف پایه':
      - 'انواع وسیله نقلیه': transportation-management/master-data/vehicle-type.md
