site_name: مستندات ERP تابان
site_description: توضیحات پروژه شما اینجا قرار می‌گیرد.
site_author: تابان‌سافت
site_url: https://docs.tabansoft.ir
repo_url: https://github.com/tabansoft/taban-erp-docs/

theme:
  name: material
  language: fa
  direction: rtl
  font:
    text: Vazirmatn
    code: Fira Code

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

# اضافه کردن کتابخانه جاوااسکریپت Mermaid
extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - javascripts/katex.js # فایل تنظیمات جدید ما
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js


extra_css:
    - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css # استایل‌های کاتک
    - stylesheets/extra.css

nav:
  - "معرفی": index.md
  - "ساختار سازمان":
      - "ساختار مالی":
          - "بنگاه‌های اقتصادی": enterprise-structure/financial/legal-entity.md
      - "ساختار عملیاتی":
          - "مکان‌های عملیاتی": enterprise-structure/operational/operating-unit.md
  - "مالی":
      - "خزانه‌داری":
          - "معرفی ماژول خزانه‌داری": "financial/treasury/overview.md"
          - "تعاریف پایه":
              - "صندوق‌های نقدی": financial/treasury/master-data/cash-box.md
              - "صندوق‌های اسناد": financial/treasury/master-data/document-box.md
              - "بانک‌ها": financial/treasury/master-data/bank.md
              - "‌شعب بانک‌ها": financial/treasury/master-data/bank-branch.md
              - "حساب‌های بانکی": financial/treasury/master-data/bank-account.md
              - "دسته‌چک‌ها": financial/treasury/master-data/checkbook.md
              - "روش‌های پرداخت": financial/treasury/master-data/payment-method.md
          - "مدیریت چک‌های دریافتی":
              - "مقدمه": financial/treasury/received-check-management/overview.md
              - "دریافت چک جدید": financial/treasury/received-check-management/receipt-check.md
              - "واگذاری چک به بانک": financial/treasury/received-check-management/deposite-check.md
              - "اعلام وصول/برگشت چک": financial/treasury/received-check-management/clearance-check.md
              - "خرج کردن چک": financial/treasury/received-check-management/endorsement-check.md
              - "استرداد چک": financial/treasury/received-check-management/return-check.md
          - "عملیات":
              - "پرداخت‌ها": financial/treasury/operations/payment-voucher.md
              - "دریافت‌ها": financial/treasury/operations/receipt-voucher.md
              - "انتقال‌ها": financial/treasury/operations/transfer-voucher.md
              - "تسویه حساب": financial/treasury/operations/settlement.md

          - "عملیات دوره‌ای":
              - "مغایرت بانکی": financial/treasury/periodic-operations/bank-reconciliation.md
      - "حسابداری":
          - "معرفی ماژول حسابداری": "financial/accounting/overview.md"
  # - 'فروش':
  #   - 'اطلاعات پایه':
  #     - 'واحد فروش': sales/operational/operating-unit.md
  #     - 'کانال توزیع': sales/operational/operating-unit.md
  #     - 'مشتری': sales/operational/operating-unit.md
  #   - 'سفارش فروش': sales/operational/operating-unit.md
  # - 'قیمت‌گذاری':
  #   - 'لیست قیمت': sales/operational/operating-unit.md
  #   - 'تعدیلات قیمت': sales/operational/operating-unit.md
  #   - 'قوانین تعدیلات قیمت': sales/operational/operating-unit.md

  - "مدیریت موجودی":
      - "تعاریف پایه":
          - "انواع بسته‌بندی کالا": inventory-management/master-data/package-type.md

  - "مدیریت انبار":
      - "تعاریف پایه":
          - "انواع بسته‌بندی کالا": inventory-management/master-data/package-type.md

  - "برنامه‌ریزی و کنترل تولید":
      - "تعاریف پایه":
          - "قابلیت‌ها": manufacturing/master-data/capability.md
          - "انواع منبع": manufacturing/master-data/resource-type.md
          - "منابع": manufacturing/master-data/resource.md
          - "مراکز کار": manufacturing/master-data/work-center.md
          - "قواعد تخصیص": manufacturing/master-data/dispatching-rule.md
          - "موتور زمان‌بندی": manufacturing/master-data/sheduler.md
      - "مهندسی تولید":
          - "فرمول‌های تولید": manufacturing/production-engineering/bom.md
          - "فرآیند‌های تولید": manufacturing/production-engineering/routing.md
      - "برنامه‌ریزی":
          - "برنامه‌های تولید اصلی": manufacturing/planning/master-production-schedules.md
      - "اجرای تولید":
          - "دستور‌های تولید": manufacturing/planning/resources.md

  - "مدیریت حمل‌ونقل":
      - "تعاریف پایه":
          - "انواع وسیله نقلیه": transportation-management/master-data/vehicle-type.md

  - "مدیریت اموال و دارایی‌های ثابت":
       - "معرفی": "fixed-asset-management/overview.md"
       - "تعاریف پایه":
          - "گروه‌های دارایی": fixed-asset-management/master-data/asset-category.md
          - "طبقه‌های دارایی": fixed-asset-management/master-data/asset-class.md
          - "دفاتر استهلاک": fixed-asset-management/master-data/depreciation-book.md
          - "تنظیمات پلاک‌دهی": fixed-asset-management/master-data/tagging-settings.md
          - "مدیریت بارکد و RFID": fixed-asset-management/master-data/asset-identification-system.md
       - "مدیریت":
          - "کارت‌های دارایی‌ها": fixed-asset-management/management/asset-master.md
       - "عملیات":
          - "تحصیل دارایی": fixed-asset-management/operations/asset-acquisition.md
          - "نقل و انتقال دارایی": fixed-asset-management/operations/asset-transfer.md
          - "تغییر وضعیت دارایی": fixed-asset-management/operations/asset-status-change.md
          - "اموال‌گردانی": fixed-asset-management/operations/asset-physical-inventory.md
          - "محاسبه استهلاک": fixed-asset-management/operations/depreciation-run.md
          - "خروج دارایی":
            - "مقدمه": fixed-asset-management/operations/asset-disposal/overview.md
            - "فروش دارایی": fixed-asset-management/operations/asset-disposal/asset-sale.md
            - "اسقاط دارایی": fixed-asset-management/operations/asset-disposal/asset-scrap.md
            - "اهدا و انتقال": fixed-asset-management/operations/asset-disposal/asset-donation.md
            - "مفقودی و حوادث": fixed-asset-management/operations/asset-disposal/asset-loss.md
       - "عملیات مالی":
          - "بستن دوره": fixed-asset-management/financial-operations/fiscal-period-close.md
          - "اسناد تعدیل": fixed-asset-management/financial-operations/asset-adjustment.md
